<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MaterialesMasterSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            ['se_comercializa' => 'P', 'nombre' => 'PEPSI RET 350MLx24UN', 'md' => '101', 'material' => '80142', 'ce' => 'A012', 'untcode' => 'C24'],
            ['se_comercializa' => 'P', 'nombre' => '7UP RET 350MLx24UN', 'md' => '101', 'material' => '80147', 'ce' => 'A012', 'untcode' => 'C24'],
            ['se_comercializa' => 'P', 'nombre' => 'PEPSI LATA 355MLx24UN', 'md' => '101', 'material' => '80624', 'ce' => 'A012', 'untcode' => 'C24'],
            ['se_comercializa' => 'P', 'nombre' => 'PEPSI LIGHT LATA 355MLx24UN', 'md' => '101', 'material' => '80625', 'ce' => 'A012', 'untcode' => 'C24'],
            ['se_comercializa' => 'P', 'nombre' => 'PEPSI PET 2Lx6UN', 'md' => '101', 'material' => '80626', 'ce' => 'A012', 'untcode' => 'C6U'],
            ['se_comercializa' => 'P', 'nombre' => 'PEPSI LIGHT PET 2Lx6UN', 'md' => '101', 'material' => '80628', 'ce' => 'A012', 'untcode' => 'C6U'],
            ['se_comercializa' => 'P', 'nombre' => 'GOLDEN KOLA PET 2Lx6UN', 'md' => '101', 'material' => '80642', 'ce' => 'A012', 'untcode' => 'C6U'],
            ['se_comercializa' => 'P', 'nombre' => 'GOLDEN KOLA LATA 355MLx24UN', 'md' => '101', 'material' => '80646', 'ce' => 'A012', 'untcode' => 'C24'],
            ['se_comercializa' => 'P', 'nombre' => 'GOLDEN MANZANA LATA 355MLx24UN', 'md' => '101', 'material' => '80648', 'ce' => 'A012', 'untcode' => 'C24'],
            ['se_comercializa' => 'P', 'nombre' => 'GOLDEN PIÑA LATA 355MLx24UN', 'md' => '101', 'material' => '80649', 'ce' => 'A012', 'untcode' => 'C24'],
            ['se_comercializa' => 'P', 'nombre' => '7UP PET 2Lx6UN', 'md' => '101', 'material' => '80674', 'ce' => 'A012', 'untcode' => 'C6U'],
            ['se_comercializa' => 'P', 'nombre' => '7UP LATA 355MLx24UN', 'md' => '101', 'material' => '80676', 'ce' => 'A012', 'untcode' => 'C24'],
            ['se_comercializa' => 'P', 'nombre' => 'MINALBA AGUA PET S/G 1,5Lx12UN', 'md' => '101', 'material' => '95722', 'ce' => 'A012', 'untcode' => 'C12'],
            ['se_comercializa' => 'P', 'nombre' => 'MINALBA AGUA PET S/G 5Lx2UN', 'md' => '101', 'material' => '95723', 'ce' => 'A012', 'untcode' => 'C2'],
            ['se_comercializa' => 'P', 'nombre' => 'MINALBA AGUA PET TR 600MLx24UN', 'md' => '101', 'material' => '123517', 'ce' => 'A012', 'untcode' => 'C24'],
            ['se_comercializa' => 'P', 'nombre' => 'ENVASE DE BOMBONA DE CO2 DE 22,7 KG', 'md' => '101', 'material' => '127779', 'ce' => 'A012', 'untcode' => 'PZA'],
            ['se_comercializa' => 'P', 'nombre' => 'ENVASE DE BOMBONA  CO2 DE 9 KG', 'md' => '101', 'material' => '127885', 'ce' => 'A012', 'untcode' => 'PZA'],
            ['se_comercializa' => 'P', 'nombre' => 'YUKERY DURAZNO LATA 335MLx24UN', 'md' => '101', 'material' => '133580', 'ce' => 'A012', 'untcode' => 'C24'],
            ['se_comercializa' => 'P', 'nombre' => 'YUKERY PERA LATA 335MLx24UN', 'md' => '101', 'material' => '133581', 'ce' => 'A012', 'untcode' => 'C24'],
            ['se_comercializa' => 'P', 'nombre' => 'YUKERY MANZANA LATA 335MLx24UN', 'md' => '101', 'material' => '133582', 'ce' => 'A012', 'untcode' => 'C24'],
            ['se_comercializa' => 'P', 'nombre' => 'PEPSI PET 1,5LX6UN', 'md' => '101', 'material' => '178392', 'ce' => 'A012', 'untcode' => 'C6U'],
            ['se_comercializa' => 'P', 'nombre' => 'GOLDEN KOLA PET 1,5LX6UN', 'md' => '101', 'material' => '178393', 'ce' => 'A012', 'untcode' => 'C6U'],
            ['se_comercializa' => 'P', 'nombre' => 'GOLDEN NARANJA PET 1,5LX6UN', 'md' => '101', 'material' => '178394', 'ce' => 'A012', 'untcode' => 'C6U'],
            ['se_comercializa' => 'P', 'nombre' => '7UP PET 1,5LX6UN', 'md' => '101', 'material' => '178395', 'ce' => 'A012', 'untcode' => 'C6U'],
            ['se_comercializa' => 'P', 'nombre' => 'GOLDEN UVA PET 1,5LX6UN', 'md' => '101', 'material' => '178396', 'ce' => 'A012', 'untcode' => 'C6U'],
            ['se_comercializa' => 'P', 'nombre' => 'GOLDEN MANZANA PET 1,5LX6UN', 'md' => '101', 'material' => '178397', 'ce' => 'A012', 'untcode' => 'C6U'],
            ['se_comercializa' => 'P', 'nombre' => 'GOLDEN PIÑA PET 1,5LX6UN', 'md' => '101', 'material' => '178398', 'ce' => 'A012', 'untcode' => 'C6U'],
            ['se_comercializa' => 'P', 'nombre' => 'GATORADE MANDARINA PET 500MLx12UN', 'md' => '101', 'material' => '178399', 'ce' => 'A012', 'untcode' => 'C12'],
            ['se_comercializa' => 'P', 'nombre' => 'GATORADE TROPICAL F PET 500MLx12UN', 'md' => '101', 'material' => '178401', 'ce' => 'A012', 'untcode' => 'C12'],
            ['se_comercializa' => 'P', 'nombre' => 'BOTELLA PEPSI 350 ML RETORNABLE USADA', 'md' => '101', 'material' => '181454', 'ce' => 'A012', 'untcode' => 'BOT'],
            ['se_comercializa' => 'P', 'nombre' => 'BOTELLA 7UP 350 ML RETORNABLE USADA', 'md' => '101', 'material' => '181456', 'ce' => 'A012', 'untcode' => 'BOT'],
            ['se_comercializa' => 'P', 'nombre' => 'YUKY-PAK MANZANA LD 250MLx24UN', 'md' => '101', 'material' => '1011283', 'ce' => 'A012', 'untcode' => 'C24'],
            ['se_comercializa' => 'P', 'nombre' => 'YUKY-PAK DURAZNO LD 250MLx24UN', 'md' => '101', 'material' => '1011284', 'ce' => 'A012', 'untcode' => 'C24'],
            ['se_comercializa' => 'P', 'nombre' => 'YUKY-PAK PERA LD 250MLx24UN', 'md' => '101', 'material' => '1011285', 'ce' => 'A012', 'untcode' => 'C24'],
            ['se_comercializa' => 'P', 'nombre' => 'LIPTON LIMON PET 500MLx12UN', 'md' => '101', 'material' => '1012201', 'ce' => 'A012', 'untcode' => 'C12'],
            ['se_comercializa' => 'P', 'nombre' => 'LIPTON DURAZNO PET 500MLx12UN', 'md' => '101', 'material' => '1012213', 'ce' => 'A012', 'untcode' => 'C12'],
            ['se_comercializa' => 'P', 'nombre' => 'YUK. MANZANA C.P. BOT 250MLX12UN', 'md' => '101', 'material' => '1012522', 'ce' => 'A012', 'untcode' => 'C12'],
            ['se_comercializa' => 'P', 'nombre' => 'YUK. DURAZNO C.P. BOT 250MLX12UN', 'md' => '101', 'material' => '1012523', 'ce' => 'A012', 'untcode' => 'C12'],
            ['se_comercializa' => 'P', 'nombre' => 'YUK. PERA C.P. BOT 250MLX12UN', 'md' => '101', 'material' => '1012916', 'ce' => 'A012', 'untcode' => 'C12'],
            ['se_comercializa' => 'P', 'nombre' => 'YUK. NARANJADA C.P. BOT 250MLX12UN', 'md' => '101', 'material' => '1012942', 'ce' => 'A012', 'untcode' => 'C12'],
            ['se_comercializa' => 'P', 'nombre' => 'GOLDEN UVA PET 2Lx6UN', 'md' => '101', 'material' => '1012991', 'ce' => 'A012', 'untcode' => 'C6U'],
            ['se_comercializa' => 'P', 'nombre' => 'GOLDEN KOLA RET 350MLx24UN', 'md' => '101', 'material' => '1013161', 'ce' => 'A012', 'untcode' => 'C24'],
            ['se_comercializa' => 'P', 'nombre' => 'GOLDEN PIÑA RET 350MLx24UN', 'md' => '101', 'material' => '1013162', 'ce' => 'A012', 'untcode' => 'C24'],
            ['se_comercializa' => 'P', 'nombre' => 'GOLDEN MANZANA RET 350MLx24UN', 'md' => '101', 'material' => '1013163', 'ce' => 'A012', 'untcode' => 'C24'],
            ['se_comercializa' => 'P', 'nombre' => 'GOLDEN UVA RET 350MLx24UN', 'md' => '101', 'material' => '1013164', 'ce' => 'A012', 'untcode' => 'C24'],
            ['se_comercializa' => 'P', 'nombre' => 'GOLDEN NARANJA RET 350MLx24UN', 'md' => '101', 'material' => '1013165', 'ce' => 'A012', 'untcode' => 'C24'],
            ['se_comercializa' => 'P', 'nombre' => 'MINALBA AGUA PET 355MLx24UN', 'md' => '101', 'material' => '1013371', 'ce' => 'A012', 'untcode' => 'C24'],
            ['se_comercializa' => 'P', 'nombre' => 'LIPTON TE VERDE PET 500MLx12UN', 'md' => '101', 'material' => '1015024', 'ce' => 'A012', 'untcode' => 'C12'],
            ['se_comercializa' => 'P', 'nombre' => 'GATORADE MORA PET 500MLx12UN', 'md' => '101', 'material' => '1015384', 'ce' => 'A012', 'untcode' => 'C12'],
            ['se_comercializa' => 'P', 'nombre' => 'YUKERY DURAZNO PET 500MLx12UN', 'md' => '101', 'material' => '1015711', 'ce' => 'A012', 'untcode' => 'C12'],
            ['se_comercializa' => 'P', 'nombre' => 'YUKERY MANGO PET 500MLx12UN', 'md' => '101', 'material' => '1015712', 'ce' => 'A012', 'untcode' => 'C12'],
            ['se_comercializa' => 'P', 'nombre' => 'YUKERY MANZANA PET 500MLx12UN', 'md' => '101', 'material' => '1015713', 'ce' => 'A012', 'untcode' => 'C12'],
            ['se_comercializa' => 'P', 'nombre' => 'YUKERY NARANJADA PET 1,5Lx6UN', 'md' => '101', 'material' => '1015931', 'ce' => 'A012', 'untcode' => 'C6U'],
            ['se_comercializa' => 'P', 'nombre' => 'YUKERY DURAZNO PET 1,5Lx6UN', 'md' => '101', 'material' => '1016072', 'ce' => 'A012', 'untcode' => 'C6U'],
            ['se_comercializa' => 'P', 'nombre' => 'LIPTON LIMON PET 1,5Lx6UN', 'md' => '101', 'material' => '1016081', 'ce' => 'A012', 'untcode' => 'C6U'],
            ['se_comercializa' => 'P', 'nombre' => 'LIPTON TE VERDE PET 1,5Lx6UN', 'md' => '101', 'material' => '1016082', 'ce' => 'A012', 'untcode' => 'C6U'],
            ['se_comercializa' => 'P', 'nombre' => 'LIPTON DURAZNO PET 1,5Lx6UN', 'md' => '101', 'material' => '1016083', 'ce' => 'A012', 'untcode' => 'C6U'],
            ['se_comercializa' => 'P', 'nombre' => 'PEPSI ZERO LATA 355MLX24UN', 'md' => '101', 'material' => '1016368', 'ce' => 'A012', 'untcode' => 'C24'],
            ['se_comercializa' => 'P', 'nombre' => 'YUK. MANGO C.P. BOT 250MLX12UN', 'md' => '101', 'material' => '1016381', 'ce' => 'A012', 'untcode' => 'C12'],
            ['se_comercializa' => 'P', 'nombre' => 'MINALBA SPARKLING PET 500MLx12UN', 'md' => '101', 'material' => '1016691', 'ce' => 'A012', 'untcode' => 'C12'],
            ['se_comercializa' => 'P', 'nombre' => 'MINALBA SPARKLING LIMON PET500MLx12UN', 'md' => '101', 'material' => '1016692', 'ce' => 'A012', 'untcode' => 'C12'],
            ['se_comercializa' => 'P', 'nombre' => 'YUKERY MANZANA PET 1,5Lx6UN', 'md' => '101', 'material' => '1016713', 'ce' => 'A012', 'untcode' => 'C6U'],
            ['se_comercializa' => 'P', 'nombre' => 'YUKERY PERA PET 1,5LX6UN', 'md' => '101', 'material' => '1016821', 'ce' => 'A012', 'untcode' => 'C6U'],
            ['se_comercializa' => 'P', 'nombre' => 'YUKERY NARA-MANGO PET 1,5LX6UN', 'md' => '101', 'material' => '1017012', 'ce' => 'A012', 'untcode' => 'C6U'],
            ['se_comercializa' => 'P', 'nombre' => 'MINALBA SPARKLING TORONJA PET500MLx12U', 'md' => '101', 'material' => '1017031', 'ce' => 'A012', 'untcode' => 'C12'],
            ['se_comercializa' => 'P', 'nombre' => 'PEPSI PET 1Lx6UN', 'md' => '101', 'material' => '1017051', 'ce' => 'A012', 'untcode' => 'C6U'],
            ['se_comercializa' => 'P', 'nombre' => 'PEPSI RET 1,25Lx6UN', 'md' => '101', 'material' => '1017052', 'ce' => 'A012', 'untcode' => 'C6U'],
            ['se_comercializa' => 'P', 'nombre' => 'GOLDEN KOLA PET 1Lx6UN', 'md' => '101', 'material' => '1017221', 'ce' => 'A012', 'untcode' => 'C6U'],
            ['se_comercializa' => 'P', 'nombre' => 'GOLDEN MANZANA PET 2Lx6UN', 'md' => '101', 'material' => '1017231', 'ce' => 'A012', 'untcode' => 'C6U'],
            ['se_comercializa' => 'P', 'nombre' => 'MINALBA SPARKLING PET 1Lx6UN', 'md' => '101', 'material' => '1017271', 'ce' => 'A012', 'untcode' => 'C6U'],
            ['se_comercializa' => 'P', 'nombre' => 'MINALBA SPARKLING LIMON PET 1Lx6UN', 'md' => '101', 'material' => '1017272', 'ce' => 'A012', 'untcode' => 'C6U'],
            ['se_comercializa' => 'P', 'nombre' => '7UP PET 1LX6UN', 'md' => '101', 'material' => '1017371', 'ce' => 'A012', 'untcode' => 'C6U'],
            ['se_comercializa' => 'P', 'nombre' => 'YUKY-PAK FRESA LD 250MLx24UN', 'md' => '101', 'material' => '1017432', 'ce' => 'A012', 'untcode' => 'C24'],
            ['se_comercializa' => 'P', 'nombre' => 'GOLDEN MANZANA PET 1Lx6UN', 'md' => '101', 'material' => '1017632', 'ce' => 'A012', 'untcode' => 'C6U'],
            ['se_comercializa' => 'P', 'nombre' => 'MINALBA SPARKLING NARANJA PET500MLx12U', 'md' => '101', 'material' => '1017662', 'ce' => 'A012', 'untcode' => 'C12'],
            ['se_comercializa' => 'P', 'nombre' => 'MINALBA SPARKLING SODA LAT355MLx24UN', 'md' => '101', 'material' => '1017751', 'ce' => 'A012', 'untcode' => 'C24'],
            ['se_comercializa' => 'P', 'nombre' => 'GOLDEN PIÑA PET 1Lx6UN', 'md' => '101', 'material' => '1017871', 'ce' => 'A012', 'untcode' => 'C6U'],
            ['se_comercializa' => 'P', 'nombre' => 'YUKERY PERA PET 500MLx12UN', 'md' => '101', 'material' => '1017961', 'ce' => 'A012', 'untcode' => 'C12'],
            ['se_comercializa' => 'P', 'nombre' => '7UP RET 1,25Lx6UN', 'md' => '101', 'material' => '1017983', 'ce' => 'A012', 'untcode' => 'C6U'],
            ['se_comercializa' => 'P', 'nombre' => 'GOLDEN KOLA RET 1,25Lx6UN', 'md' => '101', 'material' => '1017984', 'ce' => 'A012', 'untcode' => 'C6U'],
            ['se_comercializa' => 'P', 'nombre' => 'PEPSI ZERO PET 1LX6UN', 'md' => '101', 'material' => '1017985', 'ce' => 'A012', 'untcode' => 'C6U'],
            ['se_comercializa' => 'P', 'nombre' => 'GOLDEN MANZANA RET 1,25Lx6UN', 'md' => '101', 'material' => '1017991', 'ce' => 'A012', 'untcode' => 'C6U'],
            ['se_comercializa' => 'P', 'nombre' => 'GOLDEN PIÑA PET 2Lx6UN', 'md' => '101', 'material' => '1018081', 'ce' => 'A012', 'untcode' => 'C6U'],
            ['se_comercializa' => 'P', 'nombre' => 'PEPSI ZERO PET 2Lx6UN', 'md' => '101', 'material' => '1018111', 'ce' => 'A012', 'untcode' => 'C6U'],
            ['se_comercializa' => 'P', 'nombre' => 'ROCKSTAR LATA 355MLx24UN', 'md' => '101', 'material' => '1018131', 'ce' => 'A012', 'untcode' => 'C24'],
            ['se_comercializa' => 'P', 'nombre' => 'GOLDEN EXTREME MANGO HOT LAT355MLX24UN', 'md' => '101', 'material' => '1018171', 'ce' => 'A012', 'untcode' => 'C24'],
            ['se_comercializa' => 'P', 'nombre' => 'YUKY-PAK NARANJADA S/A LD 250MLx24UN', 'md' => '101', 'material' => '1018181', 'ce' => 'A012', 'untcode' => 'C24'],
            ['se_comercializa' => 'P', 'nombre' => 'YUKERY NARANJADA S/A PET 1,5Lx6UN', 'md' => '101', 'material' => '1018182', 'ce' => 'A012', 'untcode' => 'C6U'],
            ['se_comercializa' => 'P', 'nombre' => 'YUKERY MANZANA CLARIF. S/A PET 1,5Lx6UN', 'md' => '101', 'material' => '1018183', 'ce' => 'A012', 'untcode' => 'C6U'],
            ['se_comercializa' => 'P', 'nombre' => 'GATORADE MANZANA PET 500MLx12UN', 'md' => '101', 'material' => '1018185', 'ce' => 'A012', 'untcode' => 'C12'],
            ['se_comercializa' => 'P', 'nombre' => 'GOLDEN MANGO HOT PET 1Lx6UN', 'md' => '101', 'material' => '1018212', 'ce' => 'A012', 'untcode' => 'C6U'],
            ['se_comercializa' => 'P', 'nombre' => 'MINALBA SPARKLING COCO PET500MLx12UN', 'md' => '101', 'material' => '1018262', 'ce' => 'A012', 'untcode' => 'C12'],
            ['se_comercializa' => 'P', 'nombre' => 'MINALBA SPARKLING AGUAKINA SC 355MLx24UN', 'md' => '101', 'material' => '1018271', 'ce' => 'A012', 'untcode' => 'C24'],
            ['se_comercializa' => 'P', 'nombre' => 'MINALBA SPARKLI GINGERBEER LAT355MLx24UN', 'md' => '101', 'material' => '1018441', 'ce' => 'A012', 'untcode' => 'C24'],
            ['se_comercializa' => 'P', 'nombre' => 'BOTELLA GOLDEN 350ml RETORNABLE USADA', 'md' => '101', 'material' => '12340471', 'ce' => 'A012', 'untcode' => 'BOT'],
            ['se_comercializa' => 'P', 'nombre' => 'PTN ACOND RESTAURACION 200CCX12UN', 'md' => '101', 'material' => '80308130', 'ce' => 'A012', 'untcode' => 'PZA'],
            ['se_comercializa' => 'P', 'nombre' => 'PTN ACOND 3MM RESTAURACION 170CCX12UN', 'md' => '101', 'material' => '80308153', 'ce' => 'A012', 'untcode' => 'PZA'],
            ['se_comercializa' => 'P', 'nombre' => 'PTN AMPOLLAS  15CCX3UNX6', 'md' => '101', 'material' => '80308227', 'ce' => 'A012', 'untcode' => 'PZA'],
            ['se_comercializa' => 'P', 'nombre' => 'GILLETTE ANTIT ROLL-ON RUSH 60GX12UN', 'md' => '101', 'material' => '80311972', 'ce' => 'A012', 'untcode' => 'PZA'],
            ['se_comercializa' => 'P', 'nombre' => 'SECRET ANTIT ROLL-ON PROTECT 60GX12UN', 'md' => '101', 'material' => '80321737', 'ce' => 'A012', 'untcode' => 'PZA'],
            ['se_comercializa' => 'P', 'nombre' => 'OLD SPICE SPRAY ANTIT LENA 93GX12UN', 'md' => '101', 'material' => '80330555', 'ce' => 'A012', 'untcode' => 'PZA'],
            ['se_comercializa' => 'P', 'nombre' => 'ALWAYS PROTE DIAR C/PERF 80UND 194GX12UN', 'md' => '101', 'material' => '80337548', 'ce' => 'A012', 'untcode' => 'PAQ'],
            ['se_comercializa' => 'P', 'nombre' => 'PTN SHAMPOO BAMBU 200CCX12UN', 'md' => '101', 'material' => '80342856', 'ce' => 'A012', 'untcode' => 'PZA'],
            ['se_comercializa' => 'P', 'nombre' => 'PTN SHAMPOO BAMBU 400CCX12UN', 'md' => '101', 'material' => '80342857', 'ce' => 'A012', 'untcode' => 'PZA'],
            ['se_comercializa' => 'P', 'nombre' => 'PTN ACOND BAMBU 400CCX12UN', 'md' => '101', 'material' => '80342865', 'ce' => 'A012', 'untcode' => 'PZA'],
            ['se_comercializa' => 'P', 'nombre' => 'PTN ACOND BAMBU 200CCX12UN', 'md' => '101', 'material' => '80342866', 'ce' => 'A012', 'untcode' => 'PZA'],
            ['se_comercializa' => 'P', 'nombre' => 'VENUS RISTRA SIMPLYX8UN FEM 104GX10RIS', 'md' => '101', 'material' => '80351959', 'ce' => 'A012', 'untcode' => 'RIS'],
            ['se_comercializa' => 'P', 'nombre' => 'VENUS BLISTER SIMPLYX2UN FEM 26GX12UN', 'md' => '101', 'material' => '80351964', 'ce' => 'A012', 'untcode' => 'PAQ'],
            ['se_comercializa' => 'P', 'nombre' => 'ORALB CEP 1-2-3 PAQX6UN 120GX6RIS', 'md' => '101', 'material' => '80353741', 'ce' => 'A012', 'untcode' => 'PAQ'],
            ['se_comercializa' => 'P', 'nombre' => 'GILLETTE RISTRA PB2X24UN MASC 168GX24RIS', 'md' => '101', 'material' => '80678860', 'ce' => 'A012', 'untcode' => 'RIS'],
            ['se_comercializa' => 'P', 'nombre' => 'ARIEL DET LIQ REG 800CCX9UN', 'md' => '101', 'material' => '80679160', 'ce' => 'A012', 'untcode' => 'PZA'],
            ['se_comercializa' => 'P', 'nombre' => 'ALWAYS TOALLAS ULT SUAVE NOCHE 43GX24UN', 'md' => '101', 'material' => '80679243', 'ce' => 'A012', 'untcode' => 'PAQ'],
            ['se_comercializa' => 'P', 'nombre' => 'ALWAYS TOALLAS ULTRA SECA DIA 37GX24UN', 'md' => '101', 'material' => '80679257', 'ce' => 'A012', 'untcode' => 'PAQ'],
            ['se_comercializa' => 'P', 'nombre' => 'ALWAYS TOALLAS ULT SUAVE DIA 45GX24UN', 'md' => '101', 'material' => '80679263', 'ce' => 'A012', 'untcode' => 'PAQ'],
            ['se_comercializa' => 'P', 'nombre' => 'ALWAYS TOALLAS ULTRA SECA NOCHE 45GX24UN', 'md' => '101', 'material' => '80679273', 'ce' => 'A012', 'untcode' => 'PAQ'],
            ['se_comercializa' => 'P', 'nombre' => 'ALWAYS TOALLAS ULT SUAVE NOCHE 87GX12UN', 'md' => '101', 'material' => '80680412', 'ce' => 'A012', 'untcode' => 'PAQ'],
            ['se_comercializa' => 'P', 'nombre' => 'HS SHAMPOO 2en1 LIMP RENOV 375CCX12UN', 'md' => '101', 'material' => '80680615', 'ce' => 'A012', 'untcode' => 'PZA'],
            ['se_comercializa' => 'P', 'nombre' => 'HS SHAMPOO ANTIFALL 375CCX12UN', 'md' => '101', 'material' => '80680655', 'ce' => 'A012', 'untcode' => 'PZA'],
            ['se_comercializa' => 'P', 'nombre' => 'HS SHAMPOO ANTIFALL 180CCX12UN', 'md' => '101', 'material' => '80680703', 'ce' => 'A012', 'untcode' => 'PZA'],
            ['se_comercializa' => 'P', 'nombre' => 'HS SHAMPOO LIMP RENOV 180CCX12UN', 'md' => '101', 'material' => '80680716', 'ce' => 'A012', 'untcode' => 'PZA'],
            ['se_comercializa' => 'P', 'nombre' => 'HS SHAMPOO LIMP RENOV 375CCX12UN', 'md' => '101', 'material' => '80680717', 'ce' => 'A012', 'untcode' => 'PZA'],
            ['se_comercializa' => 'P', 'nombre' => 'GILLETTE RIST HOJILL SUPERTHIN 60GX24RIS', 'md' => '101', 'material' => '80682872', 'ce' => 'A012', 'untcode' => 'RIS'],
            ['se_comercializa' => 'P', 'nombre' => 'ALWAYS TOALLAS SEDASEC F ABUND 60GX24UN', 'md' => '101', 'material' => '80684304', 'ce' => 'A012', 'untcode' => 'PAQ'],
            ['se_comercializa' => 'P', 'nombre' => 'ALWAYS PROTE DIAR LARGOS 50UND 146GX24UN', 'md' => '101', 'material' => '80684784', 'ce' => 'A012', 'untcode' => 'PAQ'],
            ['se_comercializa' => 'P', 'nombre' => 'GILLETTE RISTRA PB3X10UN MASC 120GX12RIS', 'md' => '101', 'material' => '80685855', 'ce' => 'A012', 'untcode' => 'RIS'],
            ['se_comercializa' => 'P', 'nombre' => 'GILLETTE BLISTER PB3X2UN MASC 23GX72UN', 'md' => '101', 'material' => '80685924', 'ce' => 'A012', 'untcode' => 'PAQ'],
            ['se_comercializa' => 'P', 'nombre' => 'PTN SHAMPOO COLAGENO 300CCX12UN', 'md' => '101', 'material' => '80686979', 'ce' => 'A012', 'untcode' => 'PZA'],
            ['se_comercializa' => 'P', 'nombre' => 'PTN ACOND COLAGENO 250CCX12UN', 'md' => '101', 'material' => '80687013', 'ce' => 'A012', 'untcode' => 'PZA'],
            ['se_comercializa' => 'P', 'nombre' => 'GILLETTE CLEARGEL COOLWAVE 82GX12UN', 'md' => '101', 'material' => '80692231', 'ce' => 'A012', 'untcode' => 'PZA'],
            ['se_comercializa' => 'P', 'nombre' => 'GILLETTE CLEARGEL COOLWAVE 45GX12UN', 'md' => '101', 'material' => '80692238', 'ce' => 'A012', 'untcode' => 'PZA'],
            ['se_comercializa' => 'P', 'nombre' => 'OLD SPICE BARRA ANTIT FRESH 50GX12UN', 'md' => '101', 'material' => '80694984', 'ce' => 'A012', 'untcode' => 'PZA'],
            ['se_comercializa' => 'P', 'nombre' => 'PTN SHAMPOO RESTAURACION 200CCX12UN', 'md' => '101', 'material' => '80696847', 'ce' => 'A012', 'untcode' => 'PZA'],
            ['se_comercializa' => 'P', 'nombre' => 'PTN SHAMPOO RESTAURACION 400CCX12UN', 'md' => '101', 'material' => '80696848', 'ce' => 'A012', 'untcode' => 'PZA'],
            ['se_comercializa' => 'P', 'nombre' => 'ORALB CREMADENT 100% 6X50ML 360GX4UN', 'md' => '101', 'material' => '80697417', 'ce' => 'A012', 'untcode' => 'PAQ'],
            ['se_comercializa' => 'P', 'nombre' => 'DOWNY SUAVIZANTE FLORAL 1400CCX9UN', 'md' => '101', 'material' => '80702950', 'ce' => 'A012', 'untcode' => 'PZA'],
            ['se_comercializa' => 'P', 'nombre' => 'GILLETTE MACH3 SISTEMA CARBONO 37GX30UN', 'md' => '101', 'material' => '80716175', 'ce' => 'A012', 'untcode' => 'PAQ'],
            ['se_comercializa' => 'P', 'nombre' => 'GILLETTE MACH3 CARBONO CARTUX2 16GX72UN', 'md' => '101', 'material' => '80722153', 'ce' => 'A012', 'untcode' => 'PAQ'],
            ['se_comercializa' => 'P', 'nombre' => 'HS SHAMPOO 2en1 SUAVE Y MANEJ 180CCX12UN', 'md' => '101', 'material' => '80724230', 'ce' => 'A012', 'untcode' => 'PZA'],
            ['se_comercializa' => 'P', 'nombre' => 'HS SHAMPOO 2en1 SUAVE Y MANEJ 375CCX12UN', 'md' => '101', 'material' => '80724232', 'ce' => 'A012', 'untcode' => 'PZA'],
            ['se_comercializa' => 'P', 'nombre' => 'DOWNY PERLAS DE PERFUME FRESH 141GX4UN', 'md' => '101', 'material' => '80730042', 'ce' => 'A012', 'untcode' => 'PZA'],
            ['se_comercializa' => 'P', 'nombre' => 'DOWNY SUAVIZANTE AMANECER 700CCX12UN', 'md' => '101', 'material' => '80737864', 'ce' => 'A012', 'untcode' => 'PZA'],
            ['se_comercializa' => 'P', 'nombre' => 'DOWNY SUAVIZANTE FLORAL 700CCX12UN', 'md' => '101', 'material' => '80737865', 'ce' => 'A012', 'untcode' => 'PZA'],
            ['se_comercializa' => 'P', 'nombre' => 'HS SHAMPOO ANTI COMEZON 375CCX12UN', 'md' => '101', 'material' => '80755365', 'ce' => 'A012', 'untcode' => 'PZA'],
            ['se_comercializa' => 'P', 'nombre' => 'HS SHAMPOO ANTI COMEZON 180CCX12UN', 'md' => '101', 'material' => '80755366', 'ce' => 'A012', 'untcode' => 'PZA'],
            ['se_comercializa' => 'P', 'nombre' => 'DOWNY SUAVIZANTE FLORAL 360CCX12UN', 'md' => '101', 'material' => '80756144', 'ce' => 'A012', 'untcode' => 'PZA'],
            ['se_comercializa' => 'P', 'nombre' => 'PTN CREMA PEINAR KERATINA 160CCX12UN', 'md' => '101', 'material' => '80775102', 'ce' => 'A012', 'untcode' => 'PZA'],
            ['se_comercializa' => 'P', 'nombre' => 'PTN SHAMPOO KERATINA 175CCX12UN', 'md' => '101', 'material' => '80782038', 'ce' => 'A012', 'untcode' => 'PZA'],
            ['se_comercializa' => 'P', 'nombre' => 'PTN ACOND KERATINA 175CCX12UN', 'md' => '101', 'material' => '80782039', 'ce' => 'A012', 'untcode' => 'PZA'],
            ['se_comercializa' => 'P', 'nombre' => 'HS SHAMPOO ANTI-RESEQUEDAD 180CCX12UN', 'md' => '101', 'material' => '80816347', 'ce' => 'A012', 'untcode' => 'PZA'],
            ['se_comercializa' => 'P', 'nombre' => 'DOWNY SUAVIZANTE AMANECER 360CCX12UN', 'md' => '101', 'material' => '80819224', 'ce' => 'A012', 'untcode' => 'PZA'],
            ['se_comercializa' => 'P', 'nombre' => 'ARIEL DETER TOUCH OF DOWNY COL 800GX15UN', 'md' => '101', 'material' => '80826033', 'ce' => 'A012', 'untcode' => 'PZA'],
            ['se_comercializa' => 'P', 'nombre' => 'ARIEL DETERGENTE POLVO COL 4KGX4UN', 'md' => '101', 'material' => '80826035', 'ce' => 'A012', 'untcode' => 'PZA'],
            ['se_comercializa' => 'P', 'nombre' => 'ARIEL DETERGENTE POLVO COL 800GX15UN', 'md' => '101', 'material' => '80826038', 'ce' => 'A012', 'untcode' => 'PZA'],
            ['se_comercializa' => 'P', 'nombre' => 'ARIEL DETERGENTE POLVO COL 400GX24UN', 'md' => '101', 'material' => '80826039', 'ce' => 'A012', 'untcode' => 'PZA'],
            ['se_comercializa' => 'P', 'nombre' => 'ACE DETERGENTE POLVO COL 800GX15UN', 'md' => '101', 'material' => '80826042', 'ce' => 'A012', 'untcode' => 'PZA'],
            ['se_comercializa' => 'P', 'nombre' => 'ACE DETERGENTE POLVO COL 400GX24UN', 'md' => '101', 'material' => '80826043', 'ce' => 'A012', 'untcode' => 'PZA'],
            ['se_comercializa' => 'P', 'nombre' => 'ORALB CEP INDICATOR RISTX4CEP 65GX9RIS', 'md' => '101', 'material' => '80835410', 'ce' => 'A012', 'untcode' => 'RIS'],
            ['se_comercializa' => 'P', 'nombre' => 'DOWNY SUAVIZANTE EXOTICO 700CCX12UN', 'md' => '101', 'material' => '80837948', 'ce' => 'A012', 'untcode' => 'PZA'],
            ['se_comercializa' => 'P', 'nombre' => 'DOWNY SUAVIZANTE EXOTICO 360CCX12UN', 'md' => '101', 'material' => '80844690', 'ce' => 'A012', 'untcode' => 'PZA'],
            ['se_comercializa' => 'P', 'nombre' => 'VENUS DAISY 2UND 12GX36UN', 'md' => '101', 'material' => '80864228', 'ce' => 'A012', 'untcode' => 'PZA'],
            ['se_comercializa' => 'P', 'nombre' => 'ANZOATEGUI CAFE PREMIUM 100Gx30UN', 'md' => '101', 'material' => 'C200', 'ce' => 'A012', 'untcode' => 'PAQ'],
            ['se_comercializa' => 'P', 'nombre' => 'ANZOATEGUI CAFE PREMIUM 200Gx20UN', 'md' => '101', 'material' => 'C201', 'ce' => 'A012', 'untcode' => 'PAQ'],
            ['se_comercializa' => 'P', 'nombre' => 'ANZOATEGUI CAFE PREMIUM 500Gx10UN', 'md' => '101', 'material' => 'C202', 'ce' => 'A012', 'untcode' => 'PAQ'],
            ['se_comercializa' => 'P', 'nombre' => 'ANZOATEGUI CAFE PREMIUM GRANOS 1KGx5UN', 'md' => '101', 'material' => 'C203', 'ce' => 'A012', 'untcode' => 'PAQ'],
            ['se_comercializa' => 'P', 'nombre' => 'ANZOATEGUI CAFE DESCAFEINADO 200Gx20UN', 'md' => '101', 'material' => 'C208', 'ce' => 'A012', 'untcode' => 'PAQ'],
            ['se_comercializa' => 'P', 'nombre' => 'ANZOATEGUI CAFE DESCAFEINADO 500Gx10UN', 'md' => '101', 'material' => 'C209', 'ce' => 'A012', 'untcode' => 'PAQ'],
            ['se_comercializa' => 'P', 'nombre' => 'BUEN CAFE PREMIUM 100Gx30UN', 'md' => '101', 'material' => 'C210', 'ce' => 'A012', 'untcode' => 'PAQ'],
            ['se_comercializa' => 'P', 'nombre' => 'BUEN CAFE PREMIUM 200Gx20UN', 'md' => '101', 'material' => 'C211', 'ce' => 'A012', 'untcode' => 'PAQ'],
            ['se_comercializa' => 'P', 'nombre' => 'BUEN CAFE PREMIUM 500Gx10UN', 'md' => '101', 'material' => 'C213', 'ce' => 'A012', 'untcode' => 'PAQ'],
            ['se_comercializa' => 'P', 'nombre' => 'ANZOATEGUI CAFE PREMIUM 50Gx50UN', 'md' => '101', 'material' => 'C218', 'ce' => 'A012', 'untcode' => 'PAQ'],
            ['se_comercializa' => 'P', 'nombre' => 'MARGARITA ATUN ENS.MEXICANA 165Gx24UN', 'md' => '101', 'material' => 'D343', 'ce' => 'A012', 'untcode' => 'LAT'],
            ['se_comercializa' => 'P', 'nombre' => 'MARGARITA ATUN NATURAL 140Gx35UN', 'md' => '101', 'material' => 'D361', 'ce' => 'A012', 'untcode' => 'LAT'],
            ['se_comercializa' => 'P', 'nombre' => 'MARGARITA ATUN EN ACEITE 140Gx35UN', 'md' => '101', 'material' => 'D362', 'ce' => 'A012', 'untcode' => 'LAT'],
            ['se_comercializa' => 'P', 'nombre' => 'MARGARITA PEPITONA PIC. 140Gx35UN', 'md' => '101', 'material' => 'D366', 'ce' => 'A012', 'untcode' => 'LAT'],
            ['se_comercializa' => 'P', 'nombre' => 'MARGARITA SARDINA ACEITE 170Gx20UN', 'md' => '101', 'material' => 'D384', 'ce' => 'A012', 'untcode' => 'LAT'],
            ['se_comercializa' => 'P', 'nombre' => 'MARGARITA SARDINA TOMATE 170Gx20UN', 'md' => '101', 'material' => 'D386', 'ce' => 'A012', 'untcode' => 'LAT'],
            ['se_comercializa' => 'P', 'nombre' => 'MARGARITA SARDINA AHUMADA 170Gx20UN', 'md' => '101', 'material' => 'D387', 'ce' => 'A012', 'untcode' => 'LAT'],
            ['se_comercializa' => 'P', 'nombre' => 'CALIFORNIA ATUN DESMENUZADO 140Gx35UN', 'md' => '101', 'material' => 'D398', 'ce' => 'A012', 'untcode' => 'LAT'],
            ['se_comercializa' => 'P', 'nombre' => 'MARGARITA ATUN EN ACEITE 170Gx24UN', 'md' => '101', 'material' => 'D399', 'ce' => 'A012', 'untcode' => 'LAT'],
            ['se_comercializa' => 'P', 'nombre' => 'MARGARITA ATUN EN AGUA 170Gx24UN', 'md' => '101', 'material' => 'D403', 'ce' => 'A012', 'untcode' => 'LAT'],
            ['se_comercializa' => 'P', 'nombre' => 'EFE NAPOLITANO 0,830 LT', 'md' => '101', 'material' => 'E499', 'ce' => 'A012', 'untcode' => 'PZA'],
            ['se_comercializa' => 'P', 'nombre' => 'POLAR PILSEN RET 222MLx36UN', 'md' => '101', 'material' => 'F01001', 'ce' => 'A012', 'untcode' => 'CJ'],
            ['se_comercializa' => 'P', 'nombre' => 'POLAR PILSEN RET 330MLx24UN', 'md' => '101', 'material' => 'F01002', 'ce' => 'A012', 'untcode' => 'CJ'],
            ['se_comercializa' => 'P', 'nombre' => 'POLAR PILSEN LAT 250MLx24UN', 'md' => '101', 'material' => 'F01003', 'ce' => 'A012', 'untcode' => 'CJ'],
            ['se_comercializa' => 'P', 'nombre' => 'POLAR PILSEN LAT SLEEK 355MLx24UN', 'md' => '101', 'material' => 'F01083', 'ce' => 'A012', 'untcode' => 'CJ'],
            ['se_comercializa' => 'P', 'nombre' => 'SOLERA LAT 250MLx24UN', 'md' => '101', 'material' => 'F03001', 'ce' => 'A012', 'untcode' => 'CJ'],
            ['se_comercializa' => 'P', 'nombre' => 'SOLERA LIGHT RET 222MLx36UN', 'md' => '101', 'material' => 'F03014', 'ce' => 'A012', 'untcode' => 'CJ'],
            ['se_comercializa' => 'P', 'nombre' => 'SOLERA LIGHT LAT 250MLx24UN', 'md' => '101', 'material' => 'F03016', 'ce' => 'A012', 'untcode' => 'CJ'],
            ['se_comercializa' => 'P', 'nombre' => 'SOLERA RET 222MLx36UN', 'md' => '101', 'material' => 'F03030', 'ce' => 'A012', 'untcode' => 'CJ'],
            ['se_comercializa' => 'P', 'nombre' => 'SOLERA LAT 250MLx12UN', 'md' => '101', 'material' => 'F03063', 'ce' => 'A012', 'untcode' => 'CJ'],
            ['se_comercializa' => 'P', 'nombre' => 'SOLERA NR 222MLx12UN', 'md' => '101', 'material' => 'F03076', 'ce' => 'A012', 'untcode' => 'CJ'],
            ['se_comercializa' => 'P', 'nombre' => 'SOLERA LIGHT NR 222MLx12UN', 'md' => '101', 'material' => 'F03077', 'ce' => 'A012', 'untcode' => 'CJ'],
            ['se_comercializa' => 'P', 'nombre' => 'POLAR LIGHT RET 222MLx36UN', 'md' => '101', 'material' => 'F04005', 'ce' => 'A012', 'untcode' => 'CJ'],
            ['se_comercializa' => 'P', 'nombre' => 'POLAR LIGHT LAT 250MLx24UN', 'md' => '101', 'material' => 'F04014', 'ce' => 'A012', 'untcode' => 'CJ'],
            ['se_comercializa' => 'P', 'nombre' => 'POLAR LIGHT LAT SLEEK 355MLx12UN', 'md' => '101', 'material' => 'F04056', 'ce' => 'A012', 'untcode' => 'CJ'],
            ['se_comercializa' => 'P', 'nombre' => 'POLAR LIGHT LAT SLEEK 355MLx24UN', 'md' => '101', 'material' => 'F04061', 'ce' => 'A012', 'untcode' => 'CJ'],
            ['se_comercializa' => 'P', 'nombre' => 'SOLERA BOHEMIA LAT 250MLx24UN', 'md' => '101', 'material' => 'F06068', 'ce' => 'A012', 'untcode' => 'CJ'],
            ['se_comercializa' => 'P', 'nombre' => 'MALTIN POLAR RET 222MLx36UN', 'md' => '101', 'material' => 'F07001', 'ce' => 'A012', 'untcode' => 'CJ'],
            ['se_comercializa' => 'P', 'nombre' => 'MALTIN POLAR LAT 250MLx24UN', 'md' => '101', 'material' => 'F07007', 'ce' => 'A012', 'untcode' => 'CJ'],
            ['se_comercializa' => 'P', 'nombre' => 'MALTIN POLAR PET 1.5 Lx6UN', 'md' => '101', 'material' => 'F07018', 'ce' => 'A012', 'untcode' => 'CJ'],
            ['se_comercializa' => 'P', 'nombre' => 'MALTIN POLAR NR 250MLx12UN', 'md' => '101', 'material' => 'F07088', 'ce' => 'A012', 'untcode' => 'CJ'],
            ['se_comercializa' => 'P', 'nombre' => 'MALTIN POLAR LAT SLEEK 355MLx24UN', 'md' => '101', 'material' => 'F07101', 'ce' => 'A012', 'untcode' => 'CJ'],
            ['se_comercializa' => 'P', 'nombre' => 'POMAR ROSADO 0,75LXC12 (N)', 'md' => '101', 'material' => 'FN0115', 'ce' => 'A012', 'untcode' => 'BOT'],
            ['se_comercializa' => 'P', 'nombre' => 'POMAR BLANCO 0,75LxC12 (N)', 'md' => '101', 'material' => 'FN0116', 'ce' => 'A012', 'untcode' => 'BOT'],
            ['se_comercializa' => 'P', 'nombre' => 'POMAR TINTO 0,75LxC12 (N)', 'md' => '101', 'material' => 'FN0117', 'ce' => 'A012', 'untcode' => 'BOT'],
            ['se_comercializa' => 'P', 'nombre' => 'POMAR FRIZZANTE 0,75LxC12 (N)', 'md' => '101', 'material' => 'FN0301', 'ce' => 'A012', 'untcode' => 'BOT'],
            ['se_comercializa' => 'P', 'nombre' => 'POMAR FRIZZANTE ROSADO 0,75LxC12 (N)', 'md' => '101', 'material' => 'FN0304', 'ce' => 'A012', 'untcode' => 'BOT'],
            ['se_comercializa' => 'P', 'nombre' => 'POMAR FRIZZANTE AROMA A ROSAS 0,75LxC12', 'md' => '101', 'material' => 'FN0309', 'ce' => 'A012', 'untcode' => 'BOT'],
            ['se_comercializa' => 'P', 'nombre' => 'POMAR RESERVA TINTO 0,75LxC12 (N)', 'md' => '101', 'material' => 'FN0503', 'ce' => 'A012', 'untcode' => 'BOT'],
            ['se_comercializa' => 'P', 'nombre' => 'POMAR CRIANZA TINTO 0,75LxC12 (N)', 'md' => '101', 'material' => 'FN0525', 'ce' => 'A012', 'untcode' => 'BOT'],
            ['se_comercializa' => 'P', 'nombre' => 'POMAR BRUT 0,75LxC12 (N)', 'md' => '101', 'material' => 'FN0601', 'ce' => 'A012', 'untcode' => 'BOT'],
            ['se_comercializa' => 'P', 'nombre' => 'POMAR BRUT 0,75LxC12 EE (N)', 'md' => '101', 'material' => 'FN0606', 'ce' => 'A012', 'untcode' => 'BOT'],
            ['se_comercializa' => 'P', 'nombre' => 'POMAR BRUT NATURE 0,75LxC12 (N)', 'md' => '101', 'material' => 'FN0610', 'ce' => 'A012', 'untcode' => 'BOT'],
            ['se_comercializa' => 'P', 'nombre' => 'POMAR DEMISEC 0,75LxC12 (N)', 'md' => '101', 'material' => 'FN0612', 'ce' => 'A012', 'untcode' => 'BOT'],
            ['se_comercializa' => 'P', 'nombre' => 'POMAR BRUT ROSE 0,75LxC12 (N)', 'md' => '101', 'material' => 'FN0615', 'ce' => 'A012', 'untcode' => 'BOT'],
            ['se_comercializa' => 'P', 'nombre' => 'SANGRIA CAROREÑA TINTA 1,75Lx6UN', 'md' => '101', 'material' => 'FR0103', 'ce' => 'A012', 'untcode' => 'CJ'],
            ['se_comercializa' => 'P', 'nombre' => 'SANGRIA CAROREÑA BLANCA 1,75Lx6UN', 'md' => '101', 'material' => 'FR0120', 'ce' => 'A012', 'untcode' => 'CJ'],
            ['se_comercializa' => 'P', 'nombre' => 'SANGRIA CAROREÑA ROSADA 1,75Lx6UN', 'md' => '101', 'material' => 'FR0123', 'ce' => 'A012', 'untcode' => 'CJ'],
            ['se_comercializa' => 'P', 'nombre' => 'SANGRIA CAROREÑA VERANO RET222MLx36UN', 'md' => '101', 'material' => 'FR0133', 'ce' => 'A012', 'untcode' => 'CJ'],
            ['se_comercializa' => 'P', 'nombre' => 'SANGRIA CAROREÑA VERANO LAT250MLx12UN', 'md' => '101', 'material' => 'FR0137', 'ce' => 'A012', 'untcode' => 'CJ'],
            ['se_comercializa' => 'P', 'nombre' => 'SANGRIA LA QUE MANDA TINTA 1,75LX6UN', 'md' => '101', 'material' => 'FR0141', 'ce' => 'A012', 'untcode' => 'CJ'],
            ['se_comercializa' => 'P', 'nombre' => 'SANGRIA LA QUE MANDA BLANCA 1,75LX6UN', 'md' => '101', 'material' => 'FR0145', 'ce' => 'A012', 'untcode' => 'CJ'],
            ['se_comercializa' => 'P', 'nombre' => 'SANGRIA LA QUE MANDA ROSADA 1,75LX6UN', 'md' => '101', 'material' => 'FR0149', 'ce' => 'A012', 'untcode' => 'CJ'],
            ['se_comercializa' => 'P', 'nombre' => 'SANGRIA CAROREÑA VERANO BLANCA LAT250X12', 'md' => '101', 'material' => 'FR0153', 'ce' => 'A012', 'untcode' => 'CJ'],
            ['se_comercializa' => 'P', 'nombre' => 'SANGRIA CAROREÑA VERANO MOJITO LAT355x12', 'md' => '101', 'material' => 'FR0154', 'ce' => 'A012', 'untcode' => 'CJ'],
            ['se_comercializa' => 'P', 'nombre' => 'SANGRIA CAROREÑA VERANO LAT250MLx24UN', 'md' => '101', 'material' => 'FR0155', 'ce' => 'A012', 'untcode' => 'CJ'],
            ['se_comercializa' => 'P', 'nombre' => 'SANGRIA CAROREÑA VERANO BLANCA LAT250X24', 'md' => '101', 'material' => 'FR0158', 'ce' => 'A012', 'untcode' => 'CJ'],
            ['se_comercializa' => 'P', 'nombre' => 'SANGRIA CAROREÑA VERANO MOJITO LAT355x24', 'md' => '101', 'material' => 'FR0159', 'ce' => 'A012', 'untcode' => 'CJ'],
            ['se_comercializa' => 'P', 'nombre' => 'SANGRIA LA QUE MANDA TINTA LAT250MLx24UN', 'md' => '101', 'material' => 'FR0160', 'ce' => 'A012', 'untcode' => 'CJ'],
            ['se_comercializa' => 'P', 'nombre' => 'SANGRIA LA QUE MANDA BLANCA LAT250MLx24U', 'md' => '101', 'material' => 'FR0161', 'ce' => 'A012', 'untcode' => 'CJ'],
            ['se_comercializa' => 'P', 'nombre' => 'SANGRIA CAROREÑA TORONJA 1,75Lx6UN', 'md' => '101', 'material' => 'FR0162', 'ce' => 'A012', 'untcode' => 'CJ'],
            ['se_comercializa' => 'P', 'nombre' => 'PAN MEZCLA PARA CACHAPAS 500GRx12UN', 'md' => '101', 'material' => 'H172', 'ce' => 'A012', 'untcode' => 'PAQ'],
            ['se_comercializa' => 'P', 'nombre' => 'PAN MEZCLA MAIZ BLANCO Y ARROZ 1KGx20UN', 'md' => '101', 'material' => 'H173', 'ce' => 'A012', 'untcode' => 'PAQ'],
            ['se_comercializa' => 'P', 'nombre' => 'PRIMOR PASTA LARGA LINGUINI 1KGx12UN', 'md' => '101', 'material' => 'H1804', 'ce' => 'A012', 'untcode' => 'PAQ'],
            ['se_comercializa' => 'P', 'nombre' => 'PAN HPM BLANCO GLUTEN FREE 1KGX20UN VE', 'md' => '101', 'material' => 'H187', 'ce' => 'A012', 'untcode' => 'PAQ'],
            ['se_comercializa' => 'P', 'nombre' => 'PAN HPM AMARILLO GLUTEN FREE 1KGX20UN VE', 'md' => '101', 'material' => 'H188', 'ce' => 'A012', 'untcode' => 'PAQ'],
            ['se_comercializa' => 'P', 'nombre' => 'PAN SEMILLAS NUTRITIVAS 500Gx12UN', 'md' => '101', 'material' => 'H195', 'ce' => 'A012', 'untcode' => 'PAQ'],
            ['se_comercializa' => 'P', 'nombre' => 'PAN AREPITAS DULCE 500Gx12UN', 'md' => '101', 'material' => 'H196', 'ce' => 'A012', 'untcode' => 'PAQ'],
            ['se_comercializa' => 'P', 'nombre' => 'PRIMOR CREMA ARROZ ENRIQUECI 450Gx24UN', 'md' => '101', 'material' => 'H330', 'ce' => 'A012', 'untcode' => 'POT'],
            ['se_comercializa' => 'P', 'nombre' => 'PRIMOR CREMA ARROZ ENRIQUECI 900Gx12UN', 'md' => '101', 'material' => 'H331', 'ce' => 'A012', 'untcode' => 'POT'],
            ['se_comercializa' => 'P', 'nombre' => 'PRIMOR ARROZ PERLADO 900Gx24UN', 'md' => '101', 'material' => 'H368', 'ce' => 'A012', 'untcode' => 'PAQ'],
            ['se_comercializa' => 'P', 'nombre' => 'PRIMOR CREMA ARROZ BOLSA ENRIQ 900Gx12UN', 'md' => '101', 'material' => 'H371', 'ce' => 'A012', 'untcode' => 'BOL'],
            ['se_comercializa' => 'P', 'nombre' => 'PRIMOR CREMA DE ARROZ BANANA 450Gx16UN', 'md' => '101', 'material' => 'H375', 'ce' => 'A012', 'untcode' => 'BOL'],
            ['se_comercializa' => 'P', 'nombre' => 'PRIMOR CREMA DE ARROZ DURAZNO 450Gx16UN', 'md' => '101', 'material' => 'H376', 'ce' => 'A012', 'untcode' => 'BOL'],
            ['se_comercializa' => 'P', 'nombre' => 'PRIMOR ARROZ TRADICIONAL 900Gx24UN', 'md' => '101', 'material' => 'H377', 'ce' => 'A012', 'untcode' => 'PAQ'],
            ['se_comercializa' => 'P', 'nombre' => 'PRIMOR ARROZ CLÁSICO SUPERIOR 900Gx24UN', 'md' => '101', 'material' => 'H378', 'ce' => 'A012', 'untcode' => 'PAQ'],
            ['se_comercializa' => 'P', 'nombre' => 'PRIMOR CREMA ARROZ BOLSA ENRIQ 225Gx20UN', 'md' => '101', 'material' => 'H380', 'ce' => 'A012', 'untcode' => 'BOL'],
            ['se_comercializa' => 'P', 'nombre' => 'PRIMOR CREMA ARROZ BOLSA ENRIQ 450Gx16UN', 'md' => '101', 'material' => 'H381', 'ce' => 'A012', 'untcode' => 'BOL'],
            ['se_comercializa' => 'P', 'nombre' => 'PRIMOR PASTA CORTA DEDALES 1KGx12UN', 'md' => '101', 'material' => 'H500', 'ce' => 'A012', 'untcode' => 'PAQ'],
            ['se_comercializa' => 'P', 'nombre' => 'PRIMOR PASTA CORTA TORNILLO 1KGx12UN', 'md' => '101', 'material' => 'H501', 'ce' => 'A012', 'untcode' => 'PAQ'],
            ['se_comercializa' => 'P', 'nombre' => 'PRIMOR PASTA CORTA MACARRON 1KGx12UN', 'md' => '101', 'material' => 'H502', 'ce' => 'A012', 'untcode' => 'PAQ'],
            ['se_comercializa' => 'P', 'nombre' => 'PRIMOR PASTA CORTA PLUMITAS 1KGx12UN', 'md' => '101', 'material' => 'H506', 'ce' => 'A012', 'untcode' => 'PAQ'],
            ['se_comercializa' => 'P', 'nombre' => 'PRIMOR PASTA CORTA DEDALES 500Gx12UN', 'md' => '101', 'material' => 'H509', 'ce' => 'A012', 'untcode' => 'PAQ'],
            ['se_comercializa' => 'P', 'nombre' => 'PRIMOR PASTA CORTA PLUMITAS 500Gx12UN', 'md' => '101', 'material' => 'H515', 'ce' => 'A012', 'untcode' => 'PAQ'],
            ['se_comercializa' => 'P', 'nombre' => 'PRIMOR PASTA LARGA VERMICELL 500Gx12UN', 'md' => '101', 'material' => 'H516', 'ce' => 'A012', 'untcode' => 'PAQ'],
            ['se_comercializa' => 'P', 'nombre' => 'PRIMOR PASTA L SPAGUETTI 500Gx12UN', 'md' => '101', 'material' => 'H517', 'ce' => 'A012', 'untcode' => 'PAQ'],
            ['se_comercializa' => 'P', 'nombre' => 'PRIMOR PASTA L VERMICELLI 1KGx12UN NR', 'md' => '101', 'material' => 'H689', 'ce' => 'A012', 'untcode' => 'PAQ'],
            ['se_comercializa' => 'P', 'nombre' => 'PRIMOR PASTA L SPAGUETTI 1KGx12UN', 'md' => '101', 'material' => 'H690', 'ce' => 'A012', 'untcode' => 'PAQ'],
            ['se_comercializa' => 'P', 'nombre' => 'PRIMOR EXTRA ESPECIAL VERMICELLI 1KGx12U', 'md' => '101', 'material' => 'H892', 'ce' => 'A012', 'untcode' => 'PAQ'],
            ['se_comercializa' => 'P', 'nombre' => 'PRIMOR PASTA CORTA PLUMITA EE 1KGx12UN', 'md' => '101', 'material' => 'H893', 'ce' => 'A012', 'untcode' => 'PAQ'],
            ['se_comercializa' => 'P', 'nombre' => 'PRIMOR PASTA CORTA TORNILLO EE 1KGx12UN', 'md' => '101', 'material' => 'H894', 'ce' => 'A012', 'untcode' => 'PAQ'],
            ['se_comercializa' => 'P', 'nombre' => 'PRIMOR PASTA CORTA DEDALES EE 1KGx12UN', 'md' => '101', 'material' => 'H895', 'ce' => 'A012', 'untcode' => 'PAQ'],
            ['se_comercializa' => 'P', 'nombre' => 'LAS LLAVES JABON TRAD. FLORAL 250Gx36UN', 'md' => '101', 'material' => 'L207', 'ce' => 'A012', 'untcode' => 'PNL'],
            ['se_comercializa' => 'P', 'nombre' => 'LAS LLAVES JABON  FF BEBE 160X48UN', 'md' => '101', 'material' => 'L275', 'ce' => 'A012', 'untcode' => 'PNL'],
            ['se_comercializa' => 'P', 'nombre' => 'LAS LLAVES MULTIUSO CREMA 250Gx36UN', 'md' => '101', 'material' => 'L357', 'ce' => 'A012', 'untcode' => 'TIN'],
            ['se_comercializa' => 'P', 'nombre' => 'LAS LLAVES MULTIUSO CREMA 500Gx18UN', 'md' => '101', 'material' => 'L358', 'ce' => 'A012', 'untcode' => 'TIN'],
            ['se_comercializa' => 'P', 'nombre' => 'LAS LLAVES LIMP MAREA CRISTALINA 1LX12UN', 'md' => '101', 'material' => 'L371', 'ce' => 'A012', 'untcode' => 'BOT'],
            ['se_comercializa' => 'P', 'nombre' => 'LAS LLAVES JABON TRAD. FLORAL 200Gx44UN', 'md' => '101', 'material' => 'L376', 'ce' => 'A012', 'untcode' => 'PNL'],
            ['se_comercializa' => 'P', 'nombre' => 'LAS LLAVES LIMP. MAREA CRISTA 500CCx24UN', 'md' => '101', 'material' => 'L377', 'ce' => 'A012', 'untcode' => 'BOT'],
            ['se_comercializa' => 'P', 'nombre' => 'MULTI CLEAN DETER FRAG CITRICA 5KGx4UN', 'md' => '101', 'material' => 'L384', 'ce' => 'A012', 'untcode' => 'BOL'],
            ['se_comercializa' => 'P', 'nombre' => 'LAS LLAVES LIMP BOSQUE SERENO 500CCx24UN', 'md' => '101', 'material' => 'L385', 'ce' => 'A012', 'untcode' => 'BOT'],
            ['se_comercializa' => 'P', 'nombre' => 'LAS LLAVES LIMP BOSQUE SERENO 1Lx12UN', 'md' => '101', 'material' => 'L386', 'ce' => 'A012', 'untcode' => 'BOT'],
            ['se_comercializa' => 'P', 'nombre' => 'LAS LLAVES LAV. L. ANTIBACT 500CCGx16UN', 'md' => '101', 'material' => 'L387', 'ce' => 'A012', 'untcode' => 'BOT'],
            ['se_comercializa' => 'P', 'nombre' => 'MULTI CLEAN DETER FRAG FLORAL 5KGx4UN', 'md' => '101', 'material' => 'L392', 'ce' => 'A012', 'untcode' => 'BOL'],
            ['se_comercializa' => 'P', 'nombre' => 'LAS LLAVES LIMP FRESCURA R. 1LX12UN', 'md' => '101', 'material' => 'L396', 'ce' => 'A012', 'untcode' => 'BOT'],
            ['se_comercializa' => 'P', 'nombre' => 'LAS LLAVES DETERGENTE FLORAL 400Gx16UN', 'md' => '101', 'material' => 'L406', 'ce' => 'A012', 'untcode' => 'BOL'],
            ['se_comercializa' => 'P', 'nombre' => 'LAS LLAVES DETERGENTE BEBE 400Gx16UN', 'md' => '101', 'material' => 'L407', 'ce' => 'A012', 'untcode' => 'BOL'],
            ['se_comercializa' => 'P', 'nombre' => 'LAS LLAVES DET L.ACTIVA CITRIC 400Gx16UN', 'md' => '101', 'material' => 'L410', 'ce' => 'A012', 'untcode' => 'BOL'],
            ['se_comercializa' => 'P', 'nombre' => 'LAS LLAVES DET L.ACTIVA FLORAL 400Gx16UN', 'md' => '101', 'material' => 'L411', 'ce' => 'A012', 'untcode' => 'BOL'],
            ['se_comercializa' => 'P', 'nombre' => 'LAS LLAVES DETERGENTE FLORAL 900Gx10UN', 'md' => '101', 'material' => 'L413', 'ce' => 'A012', 'untcode' => 'BOL'],
            ['se_comercializa' => 'P', 'nombre' => 'LAS LLAVES DETERGENTE BEBE 900Gx10UN', 'md' => '101', 'material' => 'L414', 'ce' => 'A012', 'untcode' => 'BOL'],
            ['se_comercializa' => 'P', 'nombre' => 'LAS LLAVES DET L.ACTIVA CITRIC 900Gx10UN', 'md' => '101', 'material' => 'L417', 'ce' => 'A012', 'untcode' => 'BOL'],
            ['se_comercializa' => 'P', 'nombre' => 'LAS LLAVES DET L.ACTIVA FLORAL 900Gx10UN', 'md' => '101', 'material' => 'L418', 'ce' => 'A012', 'untcode' => 'BOL'],
            ['se_comercializa' => 'P', 'nombre' => 'LAS LLAVES DET L.ACTIVA FLORAL 5KGx4UN', 'md' => '101', 'material' => 'L419', 'ce' => 'A012', 'untcode' => 'BOL'],
            ['se_comercializa' => 'P', 'nombre' => 'LAS LLAVES DET L.ACTIVA CITRICO 5KGx4UN', 'md' => '101', 'material' => 'L420', 'ce' => 'A012', 'untcode' => 'BOL'],
            ['se_comercializa' => 'P', 'nombre' => 'SUPER CAN CACHORRO 2KGx6UN', 'md' => '101', 'material' => 'M007', 'ce' => 'A012', 'untcode' => 'BOL'],
            ['se_comercializa' => 'P', 'nombre' => 'SUPER CAN CACHORRO 18KGx1UN', 'md' => '101', 'material' => 'M028', 'ce' => 'A012', 'untcode' => 'BOL'],
            ['se_comercializa' => 'P', 'nombre' => 'CHAMPS PERRO CARNE TACO 20KGx1UN', 'md' => '101', 'material' => 'M029', 'ce' => 'A012', 'untcode' => 'BOL'],
            ['se_comercializa' => 'P', 'nombre' => 'SUPER CAN CARNE HUESO 18KILOS', 'md' => '101', 'material' => 'M033', 'ce' => 'A012', 'untcode' => 'BOL'],
            ['se_comercializa' => 'P', 'nombre' => 'SUPER CAN POLLO 18KILOS', 'md' => '101', 'material' => 'M034', 'ce' => 'A012', 'untcode' => 'BOL'],
            ['se_comercializa' => 'P', 'nombre' => 'DOGOURMET CARNE A LA PARRILLA 18KGx1UN', 'md' => '101', 'material' => 'M324', 'ce' => 'A012', 'untcode' => 'BOL'],
            ['se_comercializa' => 'P', 'nombre' => 'DOGOURMET CARNE A LA PARRILLA 2KGx6UN', 'md' => '101', 'material' => 'M326', 'ce' => 'A012', 'untcode' => 'BOL'],
            ['se_comercializa' => 'P', 'nombre' => 'DOGOURMET POLLO A LA BRASA 18KGx1UN', 'md' => '101', 'material' => 'M327', 'ce' => 'A012', 'untcode' => 'BOL'],
            ['se_comercializa' => 'P', 'nombre' => 'DOGOURMET CACHORROS 18KGx1UN', 'md' => '101', 'material' => 'M329', 'ce' => 'A012', 'untcode' => 'BOL'],
            ['se_comercializa' => 'P', 'nombre' => 'DOGOURMET CACHORROS 2KGx6UN', 'md' => '101', 'material' => 'M330', 'ce' => 'A012', 'untcode' => 'BOL'],
            ['se_comercializa' => 'P', 'nombre' => 'DOGOURMET CARNE A LA PARRILLA 4KGx5UN', 'md' => '101', 'material' => 'M338', 'ce' => 'A012', 'untcode' => 'BOL'],
            ['se_comercializa' => 'P', 'nombre' => 'DOGOURMET POLLO A LA BRASA 4KGx5UN', 'md' => '101', 'material' => 'M339', 'ce' => 'A012', 'untcode' => 'BOL'],
            ['se_comercializa' => 'P', 'nombre' => 'SUPER CAN CARNE HUESO 4KGx5UN', 'md' => '101', 'material' => 'M340', 'ce' => 'A012', 'untcode' => 'BOL'],
            ['se_comercializa' => 'P', 'nombre' => 'DOGOURMET CARNE A LA PARRILLA 1KGx10UN', 'md' => '101', 'material' => 'M347', 'ce' => 'A012', 'untcode' => 'BOL'],
            ['se_comercializa' => 'P', 'nombre' => 'DOGOURMET ASADO NEGRO 18KGx1UN', 'md' => '101', 'material' => 'M351', 'ce' => 'A012', 'untcode' => 'BOL'],
            ['se_comercializa' => 'P', 'nombre' => 'DOGOURMET ASADO NEGRO 4KGx5UN', 'md' => '101', 'material' => 'M352', 'ce' => 'A012', 'untcode' => 'BOL'],
            ['se_comercializa' => 'P', 'nombre' => 'DOGOURMET PARRILLA MIXTA 18KGx1UN', 'md' => '101', 'material' => 'M378', 'ce' => 'A012', 'untcode' => 'BOL'],
            ['se_comercializa' => 'P', 'nombre' => 'DOGOURMET PARRILLA MIXTA 4KGx5UN', 'md' => '101', 'material' => 'M379', 'ce' => 'A012', 'untcode' => 'BOL'],
            ['se_comercializa' => 'P', 'nombre' => 'SUPER CAN CACHORROS  4KGx5UN', 'md' => '101', 'material' => 'M380', 'ce' => 'A012', 'untcode' => 'BOL'],
            ['se_comercializa' => 'P', 'nombre' => 'DONKAT GATICOS 1KGX18UND', 'md' => '101', 'material' => 'M403', 'ce' => 'A012', 'untcode' => 'BOL'],
            ['se_comercializa' => 'P', 'nombre' => 'DONKAT ADULTO 1,1KGX15UND', 'md' => '101', 'material' => 'M404', 'ce' => 'A012', 'untcode' => 'BOL'],
            ['se_comercializa' => 'P', 'nombre' => 'DONKAT ADULTO 7KGX1UND', 'md' => '101', 'material' => 'M405', 'ce' => 'A012', 'untcode' => 'BOL'],
            ['se_comercializa' => 'P', 'nombre' => 'DONKAT ADULTO 16KGx1UND', 'md' => '101', 'material' => 'M406', 'ce' => 'A012', 'untcode' => 'BOL'],
            ['se_comercializa' => 'P', 'nombre' => 'OHMAIGAT CASEROS Y DELICADOS 1,5KGX6UND', 'md' => '101', 'material' => 'M407', 'ce' => 'A012', 'untcode' => 'BOL'],
            ['se_comercializa' => 'P', 'nombre' => 'OHMAIGAT CASEROS Y DELICADOS 500Gx12UND', 'md' => '101', 'material' => 'M408', 'ce' => 'A012', 'untcode' => 'BOL'],
            ['se_comercializa' => 'P', 'nombre' => 'DONKAT GATICOS 7KGX1UND', 'md' => '101', 'material' => 'M409', 'ce' => 'A012', 'untcode' => 'BOL'],
            ['se_comercializa' => 'P', 'nombre' => 'SUPER CAN CARNE HUESO 2KGx6UN', 'md' => '101', 'material' => 'M800', 'ce' => 'A012', 'untcode' => 'BOL'],
            ['se_comercializa' => 'P', 'nombre' => 'SUPER CAN CARNE HUESO 10KGx1UN', 'md' => '101', 'material' => 'M802', 'ce' => 'A012', 'untcode' => 'BOL'],
            ['se_comercializa' => 'P', 'nombre' => 'DOGOURMET CACHORROS 10KGx1UN', 'md' => '101', 'material' => 'M803', 'ce' => 'A012', 'untcode' => 'BOL'],
            ['se_comercializa' => 'P', 'nombre' => 'DOGOURMET CARNE A LA PARRILLA 10KGx1UN', 'md' => '101', 'material' => 'M806', 'ce' => 'A012', 'untcode' => 'BOL'],
            ['se_comercializa' => 'P', 'nombre' => 'QUAKER AVENA ORIGINAL BOLSA 800Gx12UN', 'md' => '101', 'material' => 'Q002', 'ce' => 'A012', 'untcode' => 'BOL'],
            ['se_comercializa' => 'P', 'nombre' => 'QUAKER AVENA ORIGINAL BOLSA 400Gx16UN', 'md' => '101', 'material' => 'Q144', 'ce' => 'A012', 'untcode' => 'BOL'],
            ['se_comercializa' => 'P', 'nombre' => 'QUAKER HARINA DE AVENA BOLSA 400Gx16UN', 'md' => '101', 'material' => 'Q145', 'ce' => 'A012', 'untcode' => 'BOL'],
            ['se_comercializa' => 'P', 'nombre' => 'QUAKER AVENA ORIGINAL BOLSA 200Gx20UN', 'md' => '101', 'material' => 'Q146', 'ce' => 'A012', 'untcode' => 'BOL'],
            ['se_comercializa' => 'P', 'nombre' => 'TODDY BOLSA 1KGx12UN', 'md' => '101', 'material' => 'T001', 'ce' => 'A012', 'untcode' => 'BOL'],
            ['se_comercializa' => 'P', 'nombre' => 'TODDY 2KGx8UN', 'md' => '101', 'material' => 'T002', 'ce' => 'A012', 'untcode' => 'BOL'],
            ['se_comercializa' => 'P', 'nombre' => 'TODDY BOLSA 400Gx24UN', 'md' => '101', 'material' => 'T003', 'ce' => 'A012', 'untcode' => 'BOL'],
            ['se_comercializa' => 'P', 'nombre' => 'TODDY LATA 400Gx12UN', 'md' => '101', 'material' => 'T007', 'ce' => 'A012', 'untcode' => 'LAT'],
            ['se_comercializa' => 'P', 'nombre' => 'MAVESA MAYONESA 910Gx6UN', 'md' => '101', 'material' => 'T018', 'ce' => 'A012', 'untcode' => 'FCO'],
            ['se_comercializa' => 'P', 'nombre' => 'MAVESA MAYONESA 175Gx18UN', 'md' => '101', 'material' => 'T019', 'ce' => 'A012', 'untcode' => 'FCO'],
            ['se_comercializa' => 'P', 'nombre' => 'MAVESA MAYONESA 445Gx12UN', 'md' => '101', 'material' => 'T020', 'ce' => 'A012', 'untcode' => 'FCO'],
            ['se_comercializa' => 'P', 'nombre' => 'MAVESA VINAGRE DE ALCOHOL 1Lx12UN', 'md' => '101', 'material' => 'T048', 'ce' => 'A012', 'untcode' => 'BOT'],
            ['se_comercializa' => 'P', 'nombre' => 'MAVESA VINAGRE 500MLx24UN', 'md' => '101', 'material' => 'T049', 'ce' => 'A012', 'untcode' => 'BOT'],
            ['se_comercializa' => 'P', 'nombre' => 'KETCHUP PAMPERO 198 G X 24 UND', 'md' => '101', 'material' => 'T060', 'ce' => 'A012', 'untcode' => 'BOT'],
            ['se_comercializa' => 'P', 'nombre' => 'PAMPERO KETCHUP 397Gx24UN', 'md' => '101', 'material' => 'T061', 'ce' => 'A012', 'untcode' => 'BOT'],
            ['se_comercializa' => 'P', 'nombre' => 'CHEF MARGARINA C/S 5KGx1UN CFH', 'md' => '101', 'material' => 'T076', 'ce' => 'A012', 'untcode' => 'CJ'],
            ['se_comercializa' => 'P', 'nombre' => 'CHEF MARGARINA S/S 5KGx1UN CFH', 'md' => '101', 'material' => 'T080', 'ce' => 'A012', 'untcode' => 'CJ'],
            ['se_comercializa' => 'P', 'nombre' => 'MAVESA LIGERA MARGARINA 500Gx12UN', 'md' => '101', 'material' => 'T082', 'ce' => 'A012', 'untcode' => 'TIN'],
            ['se_comercializa' => 'P', 'nombre' => 'MAVESA MARGARINA 1000Gx6UN', 'md' => '101', 'material' => 'T084', 'ce' => 'A012', 'untcode' => 'TIN'],
            ['se_comercializa' => 'P', 'nombre' => 'MAVESA MARGARINA 500Gx12UN', 'md' => '101', 'material' => 'T086', 'ce' => 'A012', 'untcode' => 'TIN'],
            ['se_comercializa' => 'P', 'nombre' => 'MAVESA MAYONESA 175Gx24UN PET', 'md' => '101', 'material' => 'T409', 'ce' => 'A012', 'untcode' => 'FCO'],
            ['se_comercializa' => 'P', 'nombre' => 'CHEF OLEINA COMESTIB PALMA 18Lx1UN CFH', 'md' => '101', 'material' => 'T427', 'ce' => 'A012', 'untcode' => 'CÑT'],
            ['se_comercializa' => 'P', 'nombre' => 'PAMPERO SALSA BASE TOMATE 4,2KGx4UN CFH', 'md' => '101', 'material' => 'T449', 'ce' => 'A012', 'untcode' => 'ENV'],
            ['se_comercializa' => 'P', 'nombre' => 'TODDY ENVASE 200Gx12UN', 'md' => '101', 'material' => 'T472', 'ce' => 'A012', 'untcode' => 'ENV'],
            ['se_comercializa' => 'P', 'nombre' => 'RIKESA QUESO CHEDDAR PICANTE 200Gx18UN', 'md' => '101', 'material' => 'T485', 'ce' => 'A012', 'untcode' => 'ENV'],
            ['se_comercializa' => 'P', 'nombre' => 'MAVESA ADEREZO MAYONESA 3,6KGx4UN CFH', 'md' => '101', 'material' => 'T486', 'ce' => 'A012', 'untcode' => 'ENV'],
            ['se_comercializa' => 'P', 'nombre' => 'RIKESA QUESO CHEDDAR SQUEEZE 330Gx18UN', 'md' => '101', 'material' => 'T498', 'ce' => 'A012', 'untcode' => 'ENV'],
            ['se_comercializa' => 'P', 'nombre' => 'RIKESA QUESO TOCINETA SQUEEZE 330Gx18UN', 'md' => '101', 'material' => 'T526', 'ce' => 'A012', 'untcode' => 'ENV'],
            ['se_comercializa' => 'P', 'nombre' => 'MAVESA VINAGRE DE ALCOHOL 4Lx4UN CFH', 'md' => '101', 'material' => 'T533', 'ce' => 'A012', 'untcode' => 'ENV'],
            ['se_comercializa' => 'P', 'nombre' => 'RIKESA QUESO PARMESANO ENRIQ 200Gx18UN', 'md' => '101', 'material' => 'T565', 'ce' => 'A012', 'untcode' => 'ENV'],
            ['se_comercializa' => 'P', 'nombre' => 'TODDY BOLSA 100GX36UN', 'md' => '101', 'material' => 'T568', 'ce' => 'A012', 'untcode' => 'BOL'],
            ['se_comercializa' => 'P', 'nombre' => 'PRIMOR MARGARINA REDUCIDA CAL 500Gx12UN', 'md' => '101', 'material' => 'T586', 'ce' => 'A012', 'untcode' => 'TIN'],
            ['se_comercializa' => 'P', 'nombre' => 'NELLY MARGARINA REDUCIDA CAL 250Gx24UN', 'md' => '101', 'material' => 'T587', 'ce' => 'A012', 'untcode' => 'TIN'],
            ['se_comercializa' => 'P', 'nombre' => 'NELLY MARGARINA REDUCIDA CAL 500Gx12UN', 'md' => '101', 'material' => 'T588', 'ce' => 'A012', 'untcode' => 'TIN'],
            ['se_comercializa' => 'P', 'nombre' => 'ADORA MARGARINA REDUCIDA CAL 500Gx12UN', 'md' => '101', 'material' => 'T589', 'ce' => 'A012', 'untcode' => 'TIN'],
            ['se_comercializa' => 'P', 'nombre' => 'CHEF MANTECA 10KGx1UN CFH', 'md' => '101', 'material' => 'T593', 'ce' => 'A012', 'untcode' => 'CJ'],
            ['se_comercializa' => 'P', 'nombre' => 'MAVESA MARGARINA 250Gx24UN', 'md' => '101', 'material' => 'T595', 'ce' => 'A012', 'untcode' => 'TIN'],
            ['se_comercializa' => 'P', 'nombre' => 'RIKESA QUESO ORIGINAL 200Gx18UN', 'md' => '101', 'material' => 'T601', 'ce' => 'A012', 'untcode' => 'ENV'],
            ['se_comercializa' => 'P', 'nombre' => 'RIKESA QUESO ORIGINAL 300Gx12UN', 'md' => '101', 'material' => 'T602', 'ce' => 'A012', 'untcode' => 'ENV'],
            ['se_comercializa' => 'P', 'nombre' => 'RIKESA QUESO TOCINETA 300GX12UN', 'md' => '101', 'material' => 'T603', 'ce' => 'A012', 'untcode' => 'ENV'],
            ['se_comercializa' => 'P', 'nombre' => 'GAVERA ICE 24 BOTELLAS', 'md' => '101', 'material' => 'V00001', 'ce' => 'A012', 'untcode' => 'PZA'],
            ['se_comercializa' => 'P', 'nombre' => 'GAVERA ICE 36 BOTELLAS', 'md' => '101', 'material' => 'V00002', 'ce' => 'A012', 'untcode' => 'PZA'],
            ['se_comercializa' => 'P', 'nombre' => 'GAVERA LIGHT 36 BOTELLAS', 'md' => '101', 'material' => 'V00003', 'ce' => 'A012', 'untcode' => 'PZA'],
            ['se_comercializa' => 'P', 'nombre' => 'GAVERA MALTIN 36 BOTELLAS', 'md' => '101', 'material' => 'V00004', 'ce' => 'A012', 'untcode' => 'PZA'],
            ['se_comercializa' => 'P', 'nombre' => 'GAVERA PILSEN 24 BOTELLAS', 'md' => '101', 'material' => 'V00005', 'ce' => 'A012', 'untcode' => 'PZA'],
            ['se_comercializa' => 'P', 'nombre' => 'GAVERA PILSEN 36 BOTELLAS', 'md' => '101', 'material' => 'V00006', 'ce' => 'A012', 'untcode' => 'PZA'],
            ['se_comercializa' => 'P', 'nombre' => 'GAVERA SOLERA LIGHT 36 BOTELLAS', 'md' => '101', 'material' => 'V00009', 'ce' => 'A012', 'untcode' => 'PZA'],
            ['se_comercializa' => 'P', 'nombre' => 'GAVERA SOLERA 36 BOTELLAS', 'md' => '101', 'material' => 'V00010', 'ce' => 'A012', 'untcode' => 'PZA'],
            ['se_comercializa' => 'P', 'nombre' => 'GAVERA LIGH/ICE 24 BOT', 'md' => '101', 'material' => 'V00011', 'ce' => 'A012', 'untcode' => 'PZA'],
            ['se_comercializa' => 'P', 'nombre' => 'GAVERA PILSEN 24 BOT 355', 'md' => '101', 'material' => 'V00012', 'ce' => 'A012', 'untcode' => 'PZA'],
            ['se_comercializa' => 'P', 'nombre' => 'GAVERA SOLERA LIGHT 30', 'md' => '101', 'material' => 'V00013', 'ce' => 'A012', 'untcode' => 'PZA'],
            ['se_comercializa' => 'P', 'nombre' => 'GAVERA POLAR 18 BOTELLAS', 'md' => '101', 'material' => 'V00018', 'ce' => 'A012', 'untcode' => 'PZA'],
            ['se_comercializa' => 'P', 'nombre' => 'GAVERA CAROREÑA 36 BOTELLAS', 'md' => '101', 'material' => 'V00019', 'ce' => 'A012', 'untcode' => 'PZA'],
            ['se_comercializa' => 'P', 'nombre' => 'BOTELLA ICE 222 ML RETORNABLE', 'md' => '101', 'material' => 'V01000', 'ce' => 'A012', 'untcode' => 'BOT'],
            ['se_comercializa' => 'P', 'nombre' => 'BOTELLA ICE 330 ML RETORNABLE', 'md' => '101', 'material' => 'V01001', 'ce' => 'A012', 'untcode' => 'BOT'],
            ['se_comercializa' => 'P', 'nombre' => 'BOTELLA LIGHT 222 ML RETORNABLE', 'md' => '101', 'material' => 'V01002', 'ce' => 'A012', 'untcode' => 'BOT'],
            ['se_comercializa' => 'P', 'nombre' => 'BOTELLA  AMBAR 250 ML RETORNABLE', 'md' => '101', 'material' => 'V01003', 'ce' => 'A012', 'untcode' => 'BOT'],
            ['se_comercializa' => 'P', 'nombre' => 'BOTELLA MALTIN 222 ML RETORNABLE', 'md' => '101', 'material' => 'V01004', 'ce' => 'A012', 'untcode' => 'BOT'],
            ['se_comercializa' => 'P', 'nombre' => 'BOTELLA PILSEN 222 ML RETONABLE', 'md' => '101', 'material' => 'V01005', 'ce' => 'A012', 'untcode' => 'BOT'],
            ['se_comercializa' => 'P', 'nombre' => 'BOTELLA PILSEN 330 ML RETOR', 'md' => '101', 'material' => 'V01006', 'ce' => 'A012', 'untcode' => 'BOT'],
            ['se_comercializa' => 'P', 'nombre' => 'BOTELLA AZUL 222 ML RETORNABLE', 'md' => '101', 'material' => 'V01007', 'ce' => 'A012', 'untcode' => 'BOT'],
            ['se_comercializa' => 'P', 'nombre' => 'BOTELLA SOLERA VERDE 222 ML RETORNABLE', 'md' => '101', 'material' => 'V01008', 'ce' => 'A012', 'untcode' => 'BOT'],
            ['se_comercializa' => 'P', 'nombre' => 'BOTELLA FLINT 355 ML RET', 'md' => '101', 'material' => 'V01009', 'ce' => 'A012', 'untcode' => 'BOT'],
            ['se_comercializa' => 'P', 'nombre' => 'BOTELLA RET FLINT  222 ML', 'md' => '101', 'material' => 'V01010', 'ce' => 'A012', 'untcode' => 'BOT'],
            ['se_comercializa' => 'P', 'nombre' => 'BOTELLA FLINT 250 ML RET', 'md' => '101', 'material' => 'V01011', 'ce' => 'A012', 'untcode' => 'BOT'],
            ['se_comercializa' => 'P', 'nombre' => 'BOTELLA  PILSEN 355 RET ETIQ.', 'md' => '101', 'material' => 'V01012', 'ce' => 'A012', 'untcode' => 'BOT'],
            ['se_comercializa' => 'P', 'nombre' => 'BOTELLA FLINT 250 ML RET NUEVO PRODUCTO/', 'md' => '101', 'material' => 'V01013', 'ce' => 'A012', 'untcode' => 'BOT'],
            ['se_comercializa' => 'P', 'nombre' => 'BOTELLA PILSEN 355 ML RET.', 'md' => '101', 'material' => 'V01014', 'ce' => 'A012', 'untcode' => 'BOT'],
            ['se_comercializa' => 'P', 'nombre' => 'BARRIL INOXIDABLE 30 LTS (DIN 30 LTS)', 'md' => '101', 'material' => 'V20000', 'ce' => 'A012', 'untcode' => 'PZA'],
            ['se_comercializa' => 'P', 'nombre' => 'BARRIL INOXIDABLE 50 LTS (EURO 50 LTS)', 'md' => '101', 'material' => 'V20001', 'ce' => 'A012', 'untcode' => 'PZA'],
            ['se_comercializa' => 'P', 'nombre' => 'BOMBONAS CO2 VACIAS', 'md' => '101', 'material' => 'V30000', 'ce' => 'A012', 'untcode' => 'PZA'],
            ['se_comercializa' => 'P', 'nombre' => 'BOMBONAS CO2 LLENAS', 'md' => '101', 'material' => 'V30010', 'ce' => 'A012', 'untcode' => 'PZA'],
            ['se_comercializa' => 'P', 'nombre' => 'YOGURT FRUTA FRESA MIGURT 125GX24UND', 'md' => '101', 'material' => 'Y001', 'ce' => 'A012', 'untcode' => 'PZA'],
            ['se_comercializa' => 'P', 'nombre' => 'YOGURT FRUTA DURAZNO MIGURT 125GX24UND', 'md' => '101', 'material' => 'Y002', 'ce' => 'A012', 'untcode' => 'PZA'],
            ['se_comercializa' => 'P', 'nombre' => 'YOGURT FRUTA PIÑA MIGURT 125GX24UND', 'md' => '101', 'material' => 'Y003', 'ce' => 'A012', 'untcode' => 'PZA'],
            ['se_comercializa' => 'P', 'nombre' => 'YOGURT FRUTA FRESA MIGURT 250GX24UND', 'md' => '101', 'material' => 'Y004', 'ce' => 'A012', 'untcode' => 'BOT'],
            ['se_comercializa' => 'P', 'nombre' => 'YOGURT FRUTA DURAZNO MIGURT 250GX24UND', 'md' => '101', 'material' => 'Y005', 'ce' => 'A012', 'untcode' => 'BOT'],
            ['se_comercializa' => 'P', 'nombre' => 'YOGURT ORIGINAL MIGURT 750GX12UND', 'md' => '101', 'material' => 'Y009', 'ce' => 'A012', 'untcode' => 'BOT'],
            ['se_comercializa' => 'P', 'nombre' => 'YOGURT SABOR FRESA MIGURT 125GX24UND', 'md' => '101', 'material' => 'Y036', 'ce' => 'A012', 'untcode' => 'PZA'],
            ['se_comercializa' => 'P', 'nombre' => 'YOGURT SABOR NARANJA V-MIGURT 125GX24UND', 'md' => '101', 'material' => 'Y070', 'ce' => 'A012', 'untcode' => 'PZA'],
            ['se_comercializa' => 'P', 'nombre' => 'YOGURT SABOR DURAZNO MIGURT 125GX24UND', 'md' => '101', 'material' => 'Y073', 'ce' => 'A012', 'untcode' => 'PZA'],
            ['se_comercializa' => 'P', 'nombre' => 'YOGURT ORIGINAL MIGURT 250GX24UND', 'md' => '101', 'material' => 'Y075', 'ce' => 'A012', 'untcode' => 'BOT'],
        ];

        $inserted = 0;
        foreach ($data as $row) {
            DB::table('materiales_master')->updateOrInsert(
                ['material' => $row['material']],
                [
                    'se_comercializa' => $row['se_comercializa'],
                    'nombre'          => $row['nombre'],
                    'md'              => $row['md'],
                    'ce'              => $row['ce'],
                    'untcode'         => $row['untcode'],
                    'created_at'      => now(),
                    'updated_at'      => now(),
                ]
            );
            $inserted++;
        }

        $this->command->info("Se importaron/actualizaron {$inserted} materiales en materiales_master.");
    }
}