services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: qa-polar-api
    container_name: qa-polar_api
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      APP_SERVICE: app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "8092:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "api-qa.polar.localhost:host-gateway"
    networks:
      - polar_network
      - appnet

networks:
  polar_network:
    driver: bridge
  appnet:
    external: true
